name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  all-jobs-passed:
    runs-on: ubuntu-latest
    needs:
      - check-formatting
      - test
    steps:
      - run: exit 0

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-version:
          - 1.75.0
          - stable
      fail-fast: true
    name: Test on ${{ matrix.os }} with Rust ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@{{ matrix.rust-version }}
      - run: cargo test

